version: '3.7'

services:
  sonarqube:
    image: sonarqube:8.4-community
    container_name: sonarqube
    ports:
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://192.168.40.91:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: 123456
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions