version: '3.7'
services:
  postgresql:
    image: bitnami/postgresql:11
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - ./postgresql_data:/bitnami/postgresql