version: '3.7'

services:
  jenkins:
    image: jenkinsci/blueocean:1.18.1
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock