version: '3.7'

services:
  kong-database:
    image: postgres:9.6.11-alpine
    container_name: kong-database
    volumes:
      - ./kong_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong

  kong-migration:
    build: ./kong
    container_name: kong-migration
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    command: sh -c "(kong migrations up || kong migrations bootstrap) && touch migrations_run && sleep 30"

  kong:
    build: ./kong
    container_name: kong
    depends_on:
      - kong-database
      - kong-migration
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443

  konga-database:
    image: mongo:4.1.5
    container_name: konga-database
    volumes:
      - konga_data:/data/db
    ports:
      - 27017:27017
  konga:
    image: pantsel/konga
    container_name: konga
    depends_on:
      - konga-database
    volumes:
      - ./konga/user_seed.js:/app/user_seed.js:ro
    ports:
      - 1337:1337
    environment:
      DB_ADAPTER: mongo
      DB_DATABASE: konga
      DB_HOST: konga-database
      KONGA_SEED_USER_DATA_SOURCE_FILE: /app/user_seed.js
      NODE_ENV: production
    restart: on-failure

volumes:
  kong_data:
  konga_data:
